config/routes.rb
Rails.application.routes.draw do
  resources :tasks do
    resources :lists, only: [:create, :destroy]
  end
  devise_for :users

  root 'tasks#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :user
  belongs_to :task
end

app/models/task.rb
class Task < ApplicationRecord
  has_many :lists, dependent: :destroy
  has_many :users, through: :lists

  def list?(c_user, task)
    @list_task = List.where(user: c_user, task: task).pluck(:id).join(' ').to_s
  end
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :lists, dependent: :destroy
  has_many :tasks, through: :list
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

    def create
      @list = List.new
      @list.user_id = current_user.id
      @list.task_id = params[:task_id]
      @list.save
      puts @list
      redirect_to tasks_path, notice: 'Has completado tu tarea :)'
    end
    
    def destroy
      @list = List.find(params[:id])
      @list.destroy
      redirect_to tasks_path, notice: 'Has cancelado tarea seleccionada :/'
    end

    private

    def list_params
      params.require(:list).permit(:task_id, :user_id)
    end
    
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:show ]
  before_action :task_count, only: [:index, :show]
  before_action :task_total, only: [:index, :show]


  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all
    @in_list = List.where(user: current_user).pluck(:task_id)
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
    @list = List.where(task_id: params[:id])
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def task_count
    @task_count = List.where(user: current_user).count
  end

  def task_total
    @task_total = Task.all.count
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:name, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/to_dos_helper.rb
module ToDosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todo 18 App</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"><meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
  </head>

  <body>
    <%= render 'partials/navbar' %>
    
    <div class="container">
      <div class="mb-5">
        <br>
      </div>
        
        <% if notice.present? %>
          <div class="row">
            <div class="col-12">
              <p class="alert alert-info"><%= notice %></p>
              <p class="alert"><%= alert %></p>
            </div>
          </div>
        <% end %>

      <%= yield %>
    </div>


    

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

app/views/partials/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
  <a class="navbar-brand" href="<%= root_path %>"> <img src="http://app-prod-icarito.s3-us-west-1.amazonaws.com/wp-content/uploads/2010/03/10163300/716531.jpg" alt="Bandera Chilena" height="30vh" title="Ir a Home"> </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav ml-auto">     
      <% if user_signed_in? %>
        <li class="nav-item">
          <a href=# class="nav-link "  title="Tareas Completadas"><i class="far fa-flag" style=" color: red;"></i> <%= @task_count %>/<%= @task_total %> </a>
        </li>
        <li class="nav-item">
          <a href=# class="nav-link" > Hola otra vez <%= current_user.name %> <i class="far fa-smile-wink" style=" color: yellow;"></i></a>
        </li>
        <li class="nav-item">
          <%= link_to 'Cerrar sesión', destroy_user_session_path, method: :delete, class: 'nav-link' %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to 'Iniciar sesión', new_user_session_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Registrarse', new_user_registration_path, class: 'nav-link' %>
        </li>
      <% end %>

    </ul>
  </div>
</nav>

app/views/tasks/_form.html.erb
<%= form_with(model: task, local: true) do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.text_field :image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tasks/_list.html.erb
<h3 class="pt-3">Personas que han hecho lo mismo</h3>
<table class="table table-striped table-borderless table-hover">
    <thead class="thead-info">
        <th>Name</th>
        <th>Email</th>
    </thead>
    <tbody>
        <% @list.each do |l| %>
            <tr>
                <td><%= l.user.name %></td>
                <td><%= l.user.email %></td>
            </tr>
        <% end %>
    </tbody>
</table>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<div class="row">
  <div class="col-12">
    <h1>Actividades para el 18 </h1>

      <div class="row">
        <% @tasks.each do |task|  %>
          <div class="card col-sm-4 text-center p-3">
            <img class="card-img-top img-fluid" src="<%= task.image %>" alt="Card image cap">
            <div class="card-body">
              <h5 class="card-title"> <%= task.name %></h5>
                <% if  @in_list.include? task.id  %>
                  <%= link_to '<i class="fas fa-check"></i> Cancelar'.html_safe, task_list_path( task, task.list?(current_user, task)), method: :delete, class: 'btn btn-sm btn-danger', title: 'Quieres Cancelar esta Tarea?' %>
                <% else %>
                  <%= link_to '<i class="fas fa-check"></i> Listo'.html_safe, task_lists_path(task.id), method: :post, class: 'btn btn-sm btn-success', title: 'Quieres completar esta Tarea?' %>  
                <% end %>
              <%= link_to '<i class="fas fa-info"></i>  Detalles'.html_safe , task, class: 'btn btn-sm btn-info', title: 'Ver quienes han hecho esta actividad' %>
            </div>
          </div>
        <% end %>
      </div>

  </div>
</div>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<div class="row">
  <div class="col-6">
    <h1> <%= @task.name %></h1>
    <p> <em>Nombre actividad</em> </p>

    <img src="<%= @task.image %>" class="rounded mx-auto d-block img-fluid" alt="...">    
  </div>
  
  <div class="col-6">
    <%= render 'list' %>
  </div> 
  <div class="col-12">
    <br>
  </div>
  <%= link_to 'Back', tasks_path, class: 'btn btn-warning btn-lg' %>
</div>